package com.aitlp.author.data;

public class Author {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.ID
     *
     * @mbg.generated Sun Jul 07 22:56:49 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.NAME
     *
     * @mbg.generated Sun Jul 07 22:56:49 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.DESC
     *
     * @mbg.generated Sun Jul 07 22:56:49 CST 2019
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.TYPE
     *
     * @mbg.generated Sun Jul 07 22:56:49 CST 2019
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.ID
     *
     * @return the value of author.ID
     *
     * @mbg.generated Sun Jul 07 22:56:49 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.ID
     *
     * @param id the value for author.ID
     *
     * @mbg.generated Sun Jul 07 22:56:49 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.NAME
     *
     * @return the value of author.NAME
     *
     * @mbg.generated Sun Jul 07 22:56:49 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.NAME
     *
     * @param name the value for author.NAME
     *
     * @mbg.generated Sun Jul 07 22:56:49 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.DESC
     *
     * @return the value of author.DESC
     *
     * @mbg.generated Sun Jul 07 22:56:49 CST 2019
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.DESC
     *
     * @param desc the value for author.DESC
     *
     * @mbg.generated Sun Jul 07 22:56:49 CST 2019
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column author.TYPE
     *
     * @return the value of author.TYPE
     *
     * @mbg.generated Sun Jul 07 22:56:49 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column author.TYPE
     *
     * @param type the value for author.TYPE
     *
     * @mbg.generated Sun Jul 07 22:56:49 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}