package com.aitlp.author.data;

import java.util.ArrayList;
import java.util.List;

public class AuthorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table author
     *
     * @mbg.generated Wed Jul 24 21:29:44 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table author
     *
     * @mbg.generated Wed Jul 24 21:29:44 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table author
     *
     * @mbg.generated Wed Jul 24 21:29:44 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Wed Jul 24 21:29:44 CST 2019
     */
    public AuthorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Wed Jul 24 21:29:44 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Wed Jul 24 21:29:44 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Wed Jul 24 21:29:44 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Wed Jul 24 21:29:44 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Wed Jul 24 21:29:44 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Wed Jul 24 21:29:44 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Wed Jul 24 21:29:44 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Wed Jul 24 21:29:44 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Wed Jul 24 21:29:44 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Wed Jul 24 21:29:44 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table author
     *
     * @mbg.generated Wed Jul 24 21:29:44 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAuthorNameIsNull() {
            addCriterion("AUTHOR_NAME is null");
            return (Criteria) this;
        }

        public Criteria andAuthorNameIsNotNull() {
            addCriterion("AUTHOR_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorNameEqualTo(String value) {
            addCriterion("AUTHOR_NAME =", value, "authorName");
            return (Criteria) this;
        }

        public Criteria andAuthorNameNotEqualTo(String value) {
            addCriterion("AUTHOR_NAME <>", value, "authorName");
            return (Criteria) this;
        }

        public Criteria andAuthorNameGreaterThan(String value) {
            addCriterion("AUTHOR_NAME >", value, "authorName");
            return (Criteria) this;
        }

        public Criteria andAuthorNameGreaterThanOrEqualTo(String value) {
            addCriterion("AUTHOR_NAME >=", value, "authorName");
            return (Criteria) this;
        }

        public Criteria andAuthorNameLessThan(String value) {
            addCriterion("AUTHOR_NAME <", value, "authorName");
            return (Criteria) this;
        }

        public Criteria andAuthorNameLessThanOrEqualTo(String value) {
            addCriterion("AUTHOR_NAME <=", value, "authorName");
            return (Criteria) this;
        }

        public Criteria andAuthorNameLike(String value) {
            addCriterion("AUTHOR_NAME like", value, "authorName");
            return (Criteria) this;
        }

        public Criteria andAuthorNameNotLike(String value) {
            addCriterion("AUTHOR_NAME not like", value, "authorName");
            return (Criteria) this;
        }

        public Criteria andAuthorNameIn(List<String> values) {
            addCriterion("AUTHOR_NAME in", values, "authorName");
            return (Criteria) this;
        }

        public Criteria andAuthorNameNotIn(List<String> values) {
            addCriterion("AUTHOR_NAME not in", values, "authorName");
            return (Criteria) this;
        }

        public Criteria andAuthorNameBetween(String value1, String value2) {
            addCriterion("AUTHOR_NAME between", value1, value2, "authorName");
            return (Criteria) this;
        }

        public Criteria andAuthorNameNotBetween(String value1, String value2) {
            addCriterion("AUTHOR_NAME not between", value1, value2, "authorName");
            return (Criteria) this;
        }

        public Criteria andAuthorDescIsNull() {
            addCriterion("AUTHOR_DESC is null");
            return (Criteria) this;
        }

        public Criteria andAuthorDescIsNotNull() {
            addCriterion("AUTHOR_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorDescEqualTo(String value) {
            addCriterion("AUTHOR_DESC =", value, "authorDesc");
            return (Criteria) this;
        }

        public Criteria andAuthorDescNotEqualTo(String value) {
            addCriterion("AUTHOR_DESC <>", value, "authorDesc");
            return (Criteria) this;
        }

        public Criteria andAuthorDescGreaterThan(String value) {
            addCriterion("AUTHOR_DESC >", value, "authorDesc");
            return (Criteria) this;
        }

        public Criteria andAuthorDescGreaterThanOrEqualTo(String value) {
            addCriterion("AUTHOR_DESC >=", value, "authorDesc");
            return (Criteria) this;
        }

        public Criteria andAuthorDescLessThan(String value) {
            addCriterion("AUTHOR_DESC <", value, "authorDesc");
            return (Criteria) this;
        }

        public Criteria andAuthorDescLessThanOrEqualTo(String value) {
            addCriterion("AUTHOR_DESC <=", value, "authorDesc");
            return (Criteria) this;
        }

        public Criteria andAuthorDescLike(String value) {
            addCriterion("AUTHOR_DESC like", value, "authorDesc");
            return (Criteria) this;
        }

        public Criteria andAuthorDescNotLike(String value) {
            addCriterion("AUTHOR_DESC not like", value, "authorDesc");
            return (Criteria) this;
        }

        public Criteria andAuthorDescIn(List<String> values) {
            addCriterion("AUTHOR_DESC in", values, "authorDesc");
            return (Criteria) this;
        }

        public Criteria andAuthorDescNotIn(List<String> values) {
            addCriterion("AUTHOR_DESC not in", values, "authorDesc");
            return (Criteria) this;
        }

        public Criteria andAuthorDescBetween(String value1, String value2) {
            addCriterion("AUTHOR_DESC between", value1, value2, "authorDesc");
            return (Criteria) this;
        }

        public Criteria andAuthorDescNotBetween(String value1, String value2) {
            addCriterion("AUTHOR_DESC not between", value1, value2, "authorDesc");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeIsNull() {
            addCriterion("AUTHOR_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeIsNotNull() {
            addCriterion("AUTHOR_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeEqualTo(String value) {
            addCriterion("AUTHOR_TYPE =", value, "authorType");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeNotEqualTo(String value) {
            addCriterion("AUTHOR_TYPE <>", value, "authorType");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeGreaterThan(String value) {
            addCriterion("AUTHOR_TYPE >", value, "authorType");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeGreaterThanOrEqualTo(String value) {
            addCriterion("AUTHOR_TYPE >=", value, "authorType");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeLessThan(String value) {
            addCriterion("AUTHOR_TYPE <", value, "authorType");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeLessThanOrEqualTo(String value) {
            addCriterion("AUTHOR_TYPE <=", value, "authorType");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeLike(String value) {
            addCriterion("AUTHOR_TYPE like", value, "authorType");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeNotLike(String value) {
            addCriterion("AUTHOR_TYPE not like", value, "authorType");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeIn(List<String> values) {
            addCriterion("AUTHOR_TYPE in", values, "authorType");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeNotIn(List<String> values) {
            addCriterion("AUTHOR_TYPE not in", values, "authorType");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeBetween(String value1, String value2) {
            addCriterion("AUTHOR_TYPE between", value1, value2, "authorType");
            return (Criteria) this;
        }

        public Criteria andAuthorTypeNotBetween(String value1, String value2) {
            addCriterion("AUTHOR_TYPE not between", value1, value2, "authorType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table author
     *
     * @mbg.generated do_not_delete_during_merge Wed Jul 24 21:29:44 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table author
     *
     * @mbg.generated Wed Jul 24 21:29:44 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}