package com.aitlp.author.data;

import lombok.Data;

@Data
public class Author {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.ID
     *
     * @mbg.generated Mon Jul 29 22:16:41 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.AUTHOR_NAME
     *
     * @mbg.generated Mon Jul 29 22:16:41 CST 2019
     */
    private String authorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.DYNASTY
     *
     * @mbg.generated Mon Jul 29 22:16:41 CST 2019
     */
    private String dynasty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column author.AUTHOR_DESC
     *
     * @mbg.generated Mon Jul 29 22:16:41 CST 2019
     */
    private String authorDesc;


}