package com.aitlp.author.dao;

import com.aitlp.author.data.Author;
import com.aitlp.author.data.AuthorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component(value = "authorMapper")
public interface AuthorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Mon Jul 29 22:16:41 CST 2019
     */
    long countByExample(AuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Mon Jul 29 22:16:41 CST 2019
     */
    int deleteByExample(AuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Mon Jul 29 22:16:41 CST 2019
     */
    int insert(Author record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Mon Jul 29 22:16:41 CST 2019
     */
    int insertSelective(Author record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Mon Jul 29 22:16:41 CST 2019
     */
    List<Author> selectByExampleWithBLOBs(AuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Mon Jul 29 22:16:41 CST 2019
     */
    List<Author> selectByExample(AuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Mon Jul 29 22:16:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") Author record, @Param("example") AuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Mon Jul 29 22:16:41 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Author record, @Param("example") AuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table author
     *
     * @mbg.generated Mon Jul 29 22:16:41 CST 2019
     */
    int updateByExample(@Param("record") Author record, @Param("example") AuthorExample example);
}