package com.aitlp.shi.dao;

import com.aitlp.shi.data.Shi;
import com.aitlp.shi.data.ShiExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface ShiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shi
     *
     * @mbg.generated Tue Mar 12 17:03:04 CST 2019
     */
    long countByExample(ShiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shi
     *
     * @mbg.generated Tue Mar 12 17:03:04 CST 2019
     */
    int deleteByExample(ShiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shi
     *
     * @mbg.generated Tue Mar 12 17:03:04 CST 2019
     */
    int insert(Shi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shi
     *
     * @mbg.generated Tue Mar 12 17:03:04 CST 2019
     */
    int insertSelective(Shi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shi
     *
     * @mbg.generated Tue Mar 12 17:03:04 CST 2019
     */
    List<Shi> selectByExample(ShiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shi
     *
     * @mbg.generated Tue Mar 12 17:03:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") Shi record, @Param("example") ShiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shi
     *
     * @mbg.generated Tue Mar 12 17:03:04 CST 2019
     */
    int updateByExample(@Param("record") Shi record, @Param("example") ShiExample example);
}