package com.aitlp.poet.data;

public class PoetWithBLOBs extends Poet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poet.PARAGRAPHS
     *
     * @mbg.generated Wed Aug 21 22:20:36 CST 2019
     */
    private String paragraphs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poet.STRAINS
     *
     * @mbg.generated Wed Aug 21 22:20:36 CST 2019
     */
    private String strains;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poet.PARAGRAPHS
     *
     * @return the value of poet.PARAGRAPHS
     *
     * @mbg.generated Wed Aug 21 22:20:36 CST 2019
     */
    public String getParagraphs() {
        return paragraphs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poet.PARAGRAPHS
     *
     * @param paragraphs the value for poet.PARAGRAPHS
     *
     * @mbg.generated Wed Aug 21 22:20:36 CST 2019
     */
    public void setParagraphs(String paragraphs) {
        this.paragraphs = paragraphs == null ? null : paragraphs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poet.STRAINS
     *
     * @return the value of poet.STRAINS
     *
     * @mbg.generated Wed Aug 21 22:20:36 CST 2019
     */
    public String getStrains() {
        return strains;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poet.STRAINS
     *
     * @param strains the value for poet.STRAINS
     *
     * @mbg.generated Wed Aug 21 22:20:36 CST 2019
     */
    public void setStrains(String strains) {
        this.strains = strains == null ? null : strains.trim();
    }
}