package com.aitlp.poet.data;

public class Poet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poet.id
     *
     * @mbg.generated Sun Jul 28 09:20:57 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poet.author
     *
     * @mbg.generated Sun Jul 28 09:20:57 CST 2019
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poet.paragraphs
     *
     * @mbg.generated Sun Jul 28 09:20:57 CST 2019
     */
    private String paragraphs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poet.strains
     *
     * @mbg.generated Sun Jul 28 09:20:57 CST 2019
     */
    private String strains;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poet.title
     *
     * @mbg.generated Sun Jul 28 09:20:57 CST 2019
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poet.id
     *
     * @return the value of poet.id
     *
     * @mbg.generated Sun Jul 28 09:20:57 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poet.id
     *
     * @param id the value for poet.id
     *
     * @mbg.generated Sun Jul 28 09:20:57 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poet.author
     *
     * @return the value of poet.author
     *
     * @mbg.generated Sun Jul 28 09:20:57 CST 2019
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poet.author
     *
     * @param author the value for poet.author
     *
     * @mbg.generated Sun Jul 28 09:20:57 CST 2019
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poet.paragraphs
     *
     * @return the value of poet.paragraphs
     *
     * @mbg.generated Sun Jul 28 09:20:57 CST 2019
     */
    public String getParagraphs() {
        return paragraphs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poet.paragraphs
     *
     * @param paragraphs the value for poet.paragraphs
     *
     * @mbg.generated Sun Jul 28 09:20:57 CST 2019
     */
    public void setParagraphs(String paragraphs) {
        this.paragraphs = paragraphs == null ? null : paragraphs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poet.strains
     *
     * @return the value of poet.strains
     *
     * @mbg.generated Sun Jul 28 09:20:57 CST 2019
     */
    public String getStrains() {
        return strains;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poet.strains
     *
     * @param strains the value for poet.strains
     *
     * @mbg.generated Sun Jul 28 09:20:57 CST 2019
     */
    public void setStrains(String strains) {
        this.strains = strains == null ? null : strains.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poet.title
     *
     * @return the value of poet.title
     *
     * @mbg.generated Sun Jul 28 09:20:57 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poet.title
     *
     * @param title the value for poet.title
     *
     * @mbg.generated Sun Jul 28 09:20:57 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
}