package com.aitlp.poet.data;

public class Poet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poet.ID
     *
     * @mbg.generated Mon Jul 29 22:14:23 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poet.AUTHOR_ID
     *
     * @mbg.generated Mon Jul 29 22:14:23 CST 2019
     */
    private String authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poet.TITLE
     *
     * @mbg.generated Mon Jul 29 22:14:23 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poet.DYNASTY
     *
     * @mbg.generated Mon Jul 29 22:14:23 CST 2019
     */
    private String dynasty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poet.ID
     *
     * @return the value of poet.ID
     *
     * @mbg.generated Mon Jul 29 22:14:23 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poet.ID
     *
     * @param id the value for poet.ID
     *
     * @mbg.generated Mon Jul 29 22:14:23 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poet.AUTHOR_ID
     *
     * @return the value of poet.AUTHOR_ID
     *
     * @mbg.generated Mon Jul 29 22:14:23 CST 2019
     */
    public String getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poet.AUTHOR_ID
     *
     * @param authorId the value for poet.AUTHOR_ID
     *
     * @mbg.generated Mon Jul 29 22:14:23 CST 2019
     */
    public void setAuthorId(String authorId) {
        this.authorId = authorId == null ? null : authorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poet.TITLE
     *
     * @return the value of poet.TITLE
     *
     * @mbg.generated Mon Jul 29 22:14:23 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poet.TITLE
     *
     * @param title the value for poet.TITLE
     *
     * @mbg.generated Mon Jul 29 22:14:23 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poet.DYNASTY
     *
     * @return the value of poet.DYNASTY
     *
     * @mbg.generated Mon Jul 29 22:14:23 CST 2019
     */
    public String getDynasty() {
        return dynasty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poet.DYNASTY
     *
     * @param dynasty the value for poet.DYNASTY
     *
     * @mbg.generated Mon Jul 29 22:14:23 CST 2019
     */
    public void setDynasty(String dynasty) {
        this.dynasty = dynasty == null ? null : dynasty.trim();
    }
}