package com.aitlp.poet.dao;

import com.aitlp.poet.data.Poet;
import com.aitlp.poet.data.PoetExample;
import com.aitlp.poet.data.PoetWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component(value = "poetMapper")
public interface PoetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poet
     *
     * @mbg.generated Wed Aug 21 22:20:36 CST 2019
     */
    long countByExample(PoetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poet
     *
     * @mbg.generated Wed Aug 21 22:20:36 CST 2019
     */
    int deleteByExample(PoetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poet
     *
     * @mbg.generated Wed Aug 21 22:20:36 CST 2019
     */
    int insert(PoetWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poet
     *
     * @mbg.generated Wed Aug 21 22:20:36 CST 2019
     */
    int insertSelective(PoetWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poet
     *
     * @mbg.generated Wed Aug 21 22:20:36 CST 2019
     */
    List<PoetWithBLOBs> selectByExampleWithBLOBs(PoetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poet
     *
     * @mbg.generated Wed Aug 21 22:20:36 CST 2019
     */
    List<Poet> selectByExample(PoetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poet
     *
     * @mbg.generated Wed Aug 21 22:20:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") PoetWithBLOBs record, @Param("example") PoetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poet
     *
     * @mbg.generated Wed Aug 21 22:20:36 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") PoetWithBLOBs record, @Param("example") PoetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poet
     *
     * @mbg.generated Wed Aug 21 22:20:36 CST 2019
     */
    int updateByExample(@Param("record") Poet record, @Param("example") PoetExample example);
}