package com.aitlp.shi.data;

public class Shi {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shi.id
     *
     * @mbg.generated Tue Mar 12 17:03:04 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shi.author
     *
     * @mbg.generated Tue Mar 12 17:03:04 CST 2019
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shi.paragraphs
     *
     * @mbg.generated Tue Mar 12 17:03:04 CST 2019
     */
    private String paragraphs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shi.strains
     *
     * @mbg.generated Tue Mar 12 17:03:04 CST 2019
     */
    private String strains;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shi.title
     *
     * @mbg.generated Tue Mar 12 17:03:04 CST 2019
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shi.id
     *
     * @return the value of shi.id
     *
     * @mbg.generated Tue Mar 12 17:03:04 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shi.id
     *
     * @param id the value for shi.id
     *
     * @mbg.generated Tue Mar 12 17:03:04 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shi.author
     *
     * @return the value of shi.author
     *
     * @mbg.generated Tue Mar 12 17:03:04 CST 2019
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shi.author
     *
     * @param author the value for shi.author
     *
     * @mbg.generated Tue Mar 12 17:03:04 CST 2019
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shi.paragraphs
     *
     * @return the value of shi.paragraphs
     *
     * @mbg.generated Tue Mar 12 17:03:04 CST 2019
     */
    public String getParagraphs() {
        return paragraphs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shi.paragraphs
     *
     * @param paragraphs the value for shi.paragraphs
     *
     * @mbg.generated Tue Mar 12 17:03:04 CST 2019
     */
    public void setParagraphs(String paragraphs) {
        this.paragraphs = paragraphs == null ? null : paragraphs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shi.strains
     *
     * @return the value of shi.strains
     *
     * @mbg.generated Tue Mar 12 17:03:04 CST 2019
     */
    public String getStrains() {
        return strains;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shi.strains
     *
     * @param strains the value for shi.strains
     *
     * @mbg.generated Tue Mar 12 17:03:04 CST 2019
     */
    public void setStrains(String strains) {
        this.strains = strains == null ? null : strains.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shi.title
     *
     * @return the value of shi.title
     *
     * @mbg.generated Tue Mar 12 17:03:04 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shi.title
     *
     * @param title the value for shi.title
     *
     * @mbg.generated Tue Mar 12 17:03:04 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }
}